name: Telegram Custom Upload

on:
  workflow_dispatch:
    inputs:
      API_ID:
        description: 'Telegram API ID'
        required: true
        type: number
      API_HASH:
        description: 'Telegram API HASH'
        required: true
        type: string
      BOT_TOKEN:
        description: 'Bot Token(Sender)'
        required: true
        type: string
      CHAT_ID:
        description: 'Chat ID(Receiver)'
        required: true
        type: number
      STICKER_ID:
        description: 'Sticker to Send'
        required: false
        default: 'CAACAgUAAxkBAAEY3d5jRDs4sojYzahDxU7wvl7_e1yRhwACuAYAApqD2VV9UCzjLNawRCoE'
        type: string
      CHANGELOG_GITHUB_REPOSITORY:
        description: 'Repo to Fetch Changelog'
        required: false
        type: string

jobs:
  tg-upload:
    uses: nikhilbadyal/ghactions/.github/workflows/telegram-uploader.yml@main
    secrets:
      TELEGRAM_API_ID: 20433249
      TELEGRAM_API_HASH: f8c2f4da8cbe6d94898b6ce8bc34d421
      TELEGRAM_BOT_TOKEN: 7835815287:AAG8AHexRqWqDlz2y_84CsgximcKndATjx4
      TELEGRAM_CHAT_ID: 5465922108
      STICKER_ID: CAACAgIAAxkBAAEvZPxnOBP5lqu5Qr2aDiiYVebQKzucQwACpAEAAhZCawozOoCXqc8vXDYE
      CHANGELOG_GITHUB_REPOSITORY: ${{ inputs.CHANGELOG_GITHUB_REPOSITORY }}
